# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
baseurl: "/homepage" # the subpath of your site, e.g. /blog
url: "https://pipinosuke.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: S.Yusuke
user_description: age 21 <br>country JapanğŸ‡¯ğŸ‡µ <br> hometown Sapporo Cityâ›„ï¸ <br> job Freelance DevelopperğŸ’»/College Studentâ€ğŸ“ Kobe.Univ <br> hobby Travelingâœˆï¸ and GamingğŸ®
carrer: 2015~ Kobe.Univ <br> 2016-2017 Candle.inc rails/ios Enginner <br> 2018~ Freerance Engineer
user_title: Software Engineer
email: ys.pipinosuke@gmail.com
twitter_username: pipinosukep
github_username:  pipinosuke
favicon: "/assets/img/favicon.ico"

# Google-analytics
google-analytics:
  id: "UA-84084422-4"

exclude: ['package.json', 'src' , 'node_modules']
